"""add extra fields to Item

Revision ID: 826b756ff093
Revises: dd11ec98d905
Create Date: 2025-07-02 21:26:31.881298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '826b756ff093'
down_revision = 'dd11ec98d905'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('physical_status', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('area', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('recurring_issues', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('knowledge_level', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('support_person', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('support_time', sa.String(length=80), nullable=True))
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
        batch_op.drop_column('support_time')
        batch_op.drop_column('support_person')
        batch_op.drop_column('knowledge_level')
        batch_op.drop_column('recurring_issues')
        batch_op.drop_column('area')
        batch_op.drop_column('physical_status')

    # ### end Alembic commands ###
