"""add created_at to Ticket

Revision ID: 97b805bf5a43
Revises: 5cf8924bdde0
Create Date: 2025-07-02 20:53:45.784277

"""
from alembic import op
import sqlalchemy as sa
from datetime import datetime


# revision identifiers, used by Alembic.
revision = '97b805bf5a43'
down_revision = '5cf8924bdde0'
branch_labels = None
depends_on = None


def upgrade():
    # 1. Agrega la columna permitiendo NULLs
    op.add_column('ticket', sa.Column(
        'created_at', sa.String(length=30), nullable=True))
    # 2. Actualiza los registros existentes con la fecha actual
    op.execute(
        f"UPDATE ticket SET created_at = '{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}' WHERE created_at IS NULL"
    )
    # 3. Cambia la columna a NOT NULL
    op.alter_column('ticket', 'created_at', nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('role', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('role')

    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
