"""initial schema without unique name

Revision ID: c1d0878b1bad
Revises: 
Create Date: 2025-07-04 03:55:28.204080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1d0878b1bad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('serial', sa.String(length=50), nullable=True))
        batch_op.drop_constraint(batch_op.f('item_inventory_number_key'), type_='unique')
        batch_op.create_unique_constraint(None, ['serial'])
        batch_op.drop_column('inventory_number')

    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inventory_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint(batch_op.f('item_inventory_number_key'), ['inventory_number'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('serial')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
